export const db = {
  hotels: [
    {
      id: 1,
      name: "İstanbul Hotel",
      location: "Istanbul",
      price: 1200,
      image: "/images/hotels/hotel-1.png",
      isFavorite: false,
    },
    {
      id: 2,
      name: "İzmir Hotel",
      location: "Izmir",
      price: 1000,
      image: "/images/hotels/hotel-2.png",
      isFavorite: false,
    },
    {
      id: 3,
      name: "Ankara Hotel",
      location: "Ankara",
      price: 800,
      image: "/images/hotels/hotel-3.png",
      isFavorite: false,
    },
    {
      id: 4,
      name: "Antalya Hotel",
      location: "Antalya",
      price: 600,
      image: "/images/hotels/hotel-4.png",
      isFavorite: false,
    },
    {
      id: 5,
      name: "Muğla Hotel",
      location: "Mugla",
      price: 400,
      image: "/images/hotels/hotel-5.png",
      isFavorite: false,
    },
    {
      id: 6,
      name: "Aydın Hotel",
      location: "Aydin",
      price: 200,
      image: "/images/hotels/hotel-6.png",
      isFavorite: false,
    },
    {
      id: 7,
      name: "İstanbul Hotel",
      location: "Istanbul",
      price: 600,
      image: "/images/hotels/hotel-7.png",
      isFavorite: false,
    },
    {
      id: 8,
      name: "İzmir Hotel",
      location: "Izmir",
      price: 500,
      image: "/images/hotels/hotel-8.png",
      isFavorite: false,
    },
    {
      id: 9,
      name: "Ankara Hotel",
      location: "Ankara",
      price: 400,
      image: "/images/hotels/hotel-9.png",
      isFavorite: false,
    },
    {
      id: 10,
      name: "Antalya Hotel",
      location: "Antalya",
      price: 300,
      image: "/images/hotels/hotel-10.png",
      isFavorite: false,
    },
    {
      id: 11,
      name: "Muğla Hotel",
      location: "Mugla",
      price: 200,
      image: "/images/hotels/hotel-11.png",
      isFavorite: false,
    },
    {
      id: 12,
      name: "Aydın Hotel",
      location: "Aydin",
      price: 100,
      image: "/images/hotels/hotel-12.png",
      isFavorite: false,
    },
  ],
  cities: [
    {
      label: "Hepsi",
      value: "All",
    },
    {
      label: "İstanbul",
      value: "Istanbul",
    },
    {
      label: "İzmir",
      value: "Izmir",
    },
    {
      label: "Ankara",
      value: "Ankara",
    },
    {
      label: "Antalya",
      value: "Antalya",
    },
    {
      label: "Muğla",
      value: "Mugla",
    },
    {
      label: "Aydın",
      value: "Aydin",
    },
  ],
};
